-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#111318',
  base01 = '#0c0e13',
  base02 = '#191c20',
  base03 = '#44474e',
  base04 = '#c4c6cf',
  base05 = '#e2e2e9',
  base06 = '#2e3036',
  base07 = '#37393e',

  base08 = '#ffb4ab',
  base09 = '#dcbce1',
  base0A = '#bdc7dc',
  base0B = '#a9c7ff',
  base0C = '#563e5c',
  base0D = '#274777',
  base0E = '#3e4759',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#274777',
  fg = '#111318',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#f9d8fd',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#dcbce1',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bdc7dc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#405f90',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0c0e13',
  fg = '#a9c7ff',
})
